# Generated by Django 5.2.6 on 2025-09-09 07:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('customer_incentive', models.TextField(help_text="What's the benefit for the customer?")),
                ('deal_type', models.CharField(choices=[('commission', 'Commission Deal'), ('non_commission', 'Non-Commission Based Incentive'), ('conventional', 'Conventional Offer')], default='commission', max_length=20)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('referrer_reward', models.TextField(blank=True, help_text='What do referrers get instead of cash?')),
                ('conventional_offer', models.TextField(blank=True, help_text='What is the customer offer?')),
                ('budget_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='deal_images/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='accounts.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
