# Generated by Django 4.2.24 on 2025-09-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deal",
            options={},
        ),
        migrations.RemoveField(
            model_name="deal",
            name="budget_cap",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="commission_amount",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="conventional_offer",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="deal_type",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="description",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="image",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="referrer_reward",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="status",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="title",
        ),
        migrations.AddField(
            model_name="deal",
            name="deal_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="deal_name",
            field=models.CharField(default="deal1", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deal",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="no_reward_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("big_discount", "The discount is big enough to share."),
                    ("exclusive", "It’s exclusive / limited."),
                    ("high_demand", "It’s high-demand (people share it naturally)."),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="reward_type",
            field=models.CharField(
                choices=[
                    ("commission", "Commission (Reward)"),
                    ("no_reward", "No Reward"),
                ],
                default="comission",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deal",
            name="customer_incentive",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
