# Generated by Django 4.2.24 on 2025-09-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0002_alter_deal_options_remove_deal_budget_cap_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="deal",
            name="no_reward_reason",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="deal",
            name="reward_type",
            field=models.CharField(
                choices=[("commission", "Commission"), ("no_reward", "No Reward")],
                max_length=20,
            ),
        ),
    ]
