# Generated by Django 4.2.24 on 2025-10-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0003_deal_is_featured_alter_deal_no_reward_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="poster_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
