# Generated by Django 4.2.24 on 2025-10-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0004_deal_poster_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
