# Generated by Django 4.2.24 on 2025-09-30 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0003_deal_is_featured_alter_deal_no_reward_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("referrals", "0002_referralsubscription"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="referralsubscription",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="referralsubscription",
            name="deal",
            field=models.ForeignKey(
                default="2c3213e3-7186-4b31-9a74-a9f5f9ee411d",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="deals.deal",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="referralsubscription",
            unique_together={("deal", "referrer")},
        ),
        migrations.RemoveField(
            model_name="referralsubscription",
            name="business",
        ),
    ]
