# Generated by Django 5.2.6 on 2025-09-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(editable=False, max_length=6),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['otp_type', 'is_used', 'expires_at'], name='accounts_ot_otp_typ_ebbe7e_idx'),
        ),
    ]
