# Generated by Django 4.2.24 on 2025-09-20 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_otpverification_otp_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="business_cover_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="business_email",
            field=models.EmailField(
                default="hassan@gmail.com", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="business",
            name="business_logo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="business_phone",
            field=models.CharField(default="61478883555", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="business",
            name="designation",
            field=models.CharField(default="CEO", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="business",
            name="website",
            field=models.CharField(
                blank=True, default="www.google.com", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^\\+?1?\\d{9,15}$")
                ],
            ),
        ),
    ]
