# Generated by Django 4.2.24 on 2025-09-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_business_business_cover_url_business_business_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="business_address",
            field=models.TextField(default="NSW"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="business",
            name="registration_no",
            field=models.CharField(default="123", max_length=255),
            preserve_default=False,
        ),
    ]
