# Generated by Django 4.2.24 on 2025-09-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_business_business_address_business_registration_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="business_city",
            field=models.CharField(default="Sydney", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="business",
            name="business_country",
            field=models.CharField(default="Australia", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="business",
            name="business_state",
            field=models.CharField(default="NSW", max_length=255),
            preserve_default=False,
        ),
    ]
