# Generated by Django 4.2.24 on 2025-09-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_business_business_city_business_business_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="website",
            field=models.CharField(max_length=255),
        ),
    ]
