# Generated by Django 4.2.24 on 2025-09-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_business_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="onboarding_no_deal_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("big_discount", "The discount is big enough to share."),
                    ("exclusive", "It’s exclusive / limited."),
                    ("high_demand", "It’s high-demand (people share it naturally)."),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
