# Generated by Django 4.2.24 on 2025-09-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_business_onboarding_no_deal_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
