# Generated by Django 4.2.24 on 2025-10-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="onboarding_no_deal_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "already_discounted",
                        "Our products/services are already heavily discounted",
                    ),
                    (
                        "exclusive_offering",
                        "We offer exclusive/limited services that don’t need deals",
                    ),
                    (
                        "brand_strategy",
                        "We want to maintain premium branding without discounts",
                    ),
                    (
                        "organic_demand",
                        "We already have high demand and don’t need promotions",
                    ),
                    (
                        "testing_phase",
                        "We’re still testing the product/service before launching deals",
                    ),
                    ("other", "Other reason"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
