# Generated by Django 4.2.24 on 2025-10-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_business_onboarding_no_deal_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
