# Generated by Django 4.2.24 on 2025-10-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_business_stripe_account_id_user_stripe_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="is_onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_onboarding_completed",
            field=models.BooleanField(default=False),
        ),
    ]
